version: '3'
services:
  react-app:
    build:
      context: ./myapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  node-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - react-app
